image: elixir:1.13
build:
  stage: build
  variables:
    MIX_ENV: 'test'
    CVT_COLOR_BUILD_BENCHMARK: 'ON'
    DEBIAN_FRONTEND: 'noninteractive'
  only:
    changes:
      - c_src/**
      - lib/**
      - test/**
      - '*.exs'
      - mix.lock
      - .gitlab-ci.yml
  script:
    - DEBIAN_FRONTEND=noninteractive apt update -q -y
    - DEBIAN_FRONTEND=noninteractive apt install -y gcc g++ build-essential cmake
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get
    - mix deps.compile
    - mix compile
    - _build/test/lib/cvt_color/cmake/cvt_color_benchmark
    - OMP_NUM_THREADS=1 _build/test/lib/cvt_color/cmake/cvt_color_benchmark
    - MIX_ENV=test mix test
